export enum CHART_TYPES {
  自定义 = 'custom',
  kpi指标卡 = 'kpiCard',
  颜色表格 = 'table',
  分组表 = 'groupTable',
  迷你图 = 'mini',
  热力区域图 = 'heat',
  分区柱状图 = 'sliceColumn',
  堆积柱状图 = 'stackColumn',
  多系列柱状图 = 'seriesColumn',
  对比柱状图 = 'compareColumn',
  瀑布图 = 'waterFall',
  分区折线图 = 'sliceLine',
  多系列折线图 = 'seriesLine',
  折线雷达图 = 'radar',
  范围面积图 = 'rangeArea',
  散点图 = 'point',
  聚合气泡图 = 'bubble',
  饼图 = 'pie',
  多层饼图 = 'multiPie',
  玫瑰图 = 'rose',
  区域地图 = 'areaMap',
  点地图 = 'pointMap',
  流向地图 = 'lineMap',
  热力地图 = 'heatMap',
  矩形树图 = 'rectTree',
  词云 = 'wordCloud',
  漏斗图 = 'funnel',
  仪表盘 = 'gauge',
  箱形图 = 'box',
  桑基图 = 'sankey',
  NONE = 'none',
}

export enum CHART_ATTRS {
  颜色 = '颜色',
  大小 = '大小',
  标签 = '标签',
  提示 = '提示',
  粒度 = '粒度',
  形状 = '形状',
  热力色 = '热力色',
  连线 = '连线',
  半径 = '半径',
  角度 = '角度',
  文本 = '文本',
  仪表指针值 = '指针值',
  仪表目标值 = '目标值',
  桑基起点 = '起点',
  桑基终点 = '终点',
}
