/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseChart: typeof import('./components/charts/BaseChart.vue')['default']
    ChartSettingProp: typeof import('./components/widgets/ChartSettingProp.vue')['default']
    ChartSettingPropItem: typeof import('./components/widgets/ChartSettingPropItem.vue')['default']
    ChartSettingStyle: typeof import('./components/widgets/ChartSettingStyle.vue')['default']
    ChartSettingTabs: typeof import('./components/widgets/ChartSettingTabs.vue')['default']
    ChartTypeItem: typeof import('./components/widgets/ChartTypeItem.vue')['default']
    ChartTypeList: typeof import('./components/widgets/ChartTypeList.vue')['default']
    ChartTypePropTabs: typeof import('./components/widgets/ChartTypePropTabs.vue')['default']
    ColorPane: typeof import('./components/attrs/ColorPane.vue')['default']
    copy: typeof import('./components/widgets/Field copy.vue')['default']
    Drager: typeof import('./components/Drager.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Field: typeof import('./components/widgets/Field.vue')['default']
    FieldDragBox: typeof import('./components/widgets/FieldDragBox.vue')['default']
    FieldExpand: typeof import('./components/widgets/FieldExpand.vue')['default']
    FieldTitle: typeof import('./components/widgets/FieldTitle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IIconParkOutlineText: typeof import('~icons/icon-park-outline/text')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
